# Generated by Django 4.2.5 on 2024-02-06 20:29

from django.db import migrations, models
import django.db.models.deletion
import finance_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500, null=True)),
                ("archive", models.BooleanField(default=False)),
                ("time_create", models.DateField(default=finance_app.models.get_time)),
                ("time_update", models.DateField(default=finance_app.models.get_time)),
            ],
        ),
        migrations.CreateModel(
            name="Spent",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("price", models.FloatField()),
                ("description", models.CharField(max_length=500, null=True)),
                ("archive", models.BooleanField(default=False)),
                ("time_create", models.DateField(default=finance_app.models.get_time)),
                ("time_update", models.DateField(default=finance_app.models.get_time)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance_app.category",
                    ),
                ),
            ],
        ),
    ]
