# Generated by Django 4.2.5 on 2023-12-17 13:55

from django.db import migrations, models
import django.db.models.deletion
import finance_app.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500, null=True)),
                ("user", models.UUIDField(null=True)),
                (
                    "time_create",
                    models.DateTimeField(default=finance_app.models.get_time),
                ),
                (
                    "time_update",
                    models.DateTimeField(default=finance_app.models.get_time),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FFoodProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("amount", models.IntegerField()),
                ("price", models.IntegerField()),
                ("date", models.DateTimeField(default=finance_app.models.get_time)),
                ("month", models.TextField(default=finance_app.models.get_month)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="FoodProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("amount", models.IntegerField()),
                ("price", models.IntegerField()),
                ("date", models.DateTimeField(default=finance_app.models.get_time)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Rest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("amount", models.IntegerField()),
                ("price", models.IntegerField()),
                ("date", models.DateTimeField(default=finance_app.models.get_time)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="SStuff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("date", models.DateTimeField(default=finance_app.models.get_time)),
                ("month", models.TextField(default=finance_app.models.get_month)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Stuff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("date", models.DateTimeField(default=finance_app.models.get_time)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Stuffs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("date", models.DateTimeField(default=finance_app.models.get_time)),
                ("month", models.TextField(default=finance_app.models.get_month)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Spent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("price", models.FloatField()),
                ("description", models.CharField(max_length=500, null=True)),
                ("user", models.UUIDField(null=True)),
                (
                    "time_create",
                    models.DateTimeField(default=finance_app.models.get_time),
                ),
                (
                    "time_update",
                    models.DateTimeField(default=finance_app.models.get_time),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance_app.category",
                    ),
                ),
            ],
        ),
    ]
