# Generated by Django 4.2.5 on 2023-12-17 14:08

from django.db import migrations, models
import finance_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("finance_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="time_create",
            field=models.DateField(default=finance_app.models.get_time),
        ),
        migrations.AlterField(
            model_name="category",
            name="time_update",
            field=models.DateField(default=finance_app.models.get_time),
        ),
        migrations.AlterField(
            model_name="spent",
            name="time_create",
            field=models.DateField(default=finance_app.models.get_time),
        ),
        migrations.AlterField(
            model_name="spent",
            name="time_update",
            field=models.DateField(default=finance_app.models.get_time),
        ),
    ]
