# Generated by Django 4.2.5 on 2023-12-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance_app", "0002_alter_category_time_create_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="archive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="spent",
            name="archive",
            field=models.BooleanField(default=False),
        ),
    ]
