# Generated by Django 4.2.5 on 2023-12-19 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance_app", "0003_category_archive_spent_archive"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="user",
        ),
        migrations.RemoveField(
            model_name="spent",
            name="user",
        ),
    ]
