# Generated by Django 4.0.4 on 2022-04-30 19:05

from django.db import migrations, models
import finance_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("finance_app", "0004_rest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stuff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("date", models.DateTimeField(default=finance_app.models.get_time)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
