# Generated by Django 4.0.4 on 2022-05-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance_app", "0006_alter_foodproducts_price_alter_rest_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stuff",
            name="price",
            field=models.IntegerField(),
        ),
    ]
